<a href="https://colab.research.google.com/github/RiverAlpha/DL/blob/main/2_3_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2.3 线性代数

In [2]:
import torch

## 2.3.1 标量

In [3]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

## 2.3.2 向量

In [4]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [5]:
x[2]

tensor(2)

In [6]:
len(x)

3

In [7]:
x.shape

torch.Size([3])

## 2.3.3 矩阵

In [8]:
A = torch.arange(6).reshape(3, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [9]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [10]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

## 2.3.4 张量

In [11]:
torch.arange(24).reshape(2, 3, 4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

## 2.3.5 张量基本性质

In [12]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()  # Assign a copy of A to B by allocating new memory
A, A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [13]:
A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [14]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

## 2.3.6 缩减

In [15]:
x = torch.arange(3, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [16]:
A.shape, A.sum()

(torch.Size([2, 3]), tensor(15.))

In [17]:
A.shape, A.sum(axis=0).shape

(torch.Size([2, 3]), torch.Size([3]))

In [18]:
A.sum(axis=[0, 1]) == A.sum()  # Same as A.sum()

tensor(True)

In [19]:
A.mean(), A.sum() / A.numel()

(tensor(2.5000), tensor(2.5000))

In [20]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))

## 2.3.7 Non-Reduction Sum

In [21]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A, sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [22]:
A / sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [24]:
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [23]:
A.cumsum(axis=0)

tensor([[0., 1., 2.],
        [3., 5., 7.]])

## 2.3.8 点积

In [25]:
y = torch.ones(3, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [26]:
torch.sum(x * y)

tensor(3.)

## 2.3.9 张量与向量点积 mv

In [28]:
A,x

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([0., 1., 2.]))

In [27]:
A.shape, x.shape, torch.mv(A, x), A@x

(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

## 2.3.10 张量张量操作 mm

In [29]:
B = torch.ones(3, 4)
torch.mm(A, B), A@B

(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

## 2.3.11 归一化

In [30]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

## 2.3.13 EX

Prove that the transpose of the transpose of a matrix is the matrix itself:
.

In [32]:
import torch
A = torch.randn(3, 4)
print(torch.equal(A.T.T, A))  # 输出: True

True


Given two matrices A and B, show that sum and transposition commute:

In [33]:
B = torch.randn(3, 4)
# PyTorch 中浮点数计算可能有极小的精度误差，推荐使用 torch.allclose
print(torch.allclose(A.T + B.T, (A + B).T)) # 输出: True

True


3. 给定方阵 $A$，$A + A^\top$ 总是对称矩阵吗？

是的。 判断一个矩阵 $M$ 是否对称，只需看 $M^\top = M$ 是否成立。利用前两题的结论：令 $M = A + A^\top$，则 $M^\top = (A + A^\top)^\top$。根据习题 2 分配转置：$M^\top = A^\top + (A^\top)^\top$。根据习题 1 化简：$M^\top = A^\top + A = M$。得证。

4 & 5. 形状为 (2, 3, 4) 的张量 X，len(X) 的输出是什么？

讲解：在 Python 中，len() 函数总是返回张量的**第 0 个轴（axis=0，最外层维度）**的长度。无论张量有多少维，len() 只看第一个数字。因此形状 (2, 3, 4) 的 len(X) 输出是 2。



In [34]:
X = torch.empty(2, 3, 4)
print(len(X))  # 输出: 2

2


6. 运行 A / A.sum(axis=1) 会发生什么？

讲解：会报错（或者得到错误的结果）。

假设 $A$ 是一个形状为 (5, 4) 的矩阵。A.sum(axis=1) 是按行求和，它会把第 1 轴“压扁”，返回一个形状为 (5,) 的一维张量。

当你执行除法时，PyTorch 会触发广播机制（Broadcasting）。

广播规则要求从最右边（后向维度）开始对齐：A 的尾部是 4，而求和结果的尾部是 5。

因为 $4 \neq 5$，所以无法广播计算。正确做法是保持维度数量不变（Keepdims）：A / A.sum(axis=1, keepdims=True)，这样除数形状就变成了 (5, 1)，可以完美广播。

7-9 题：距离与范数

7. 曼哈顿距离与对角线移动讲解：

在曼哈顿的网格街道中，你不能穿墙走对角线，只能沿着水平（Avenues）和垂直（Streets）的街道走。这段距离的数学表示是 $L_1$ 范数（Manhattan distance），即坐标差的绝对值之和：$\|x\|_1 = \sum_i |x_i|$。

8. 张量 (2, 3, 4) 沿不同轴求和后的形状

讲解：沿着哪个轴求和，哪个轴的维度就会消失（被折叠）：

沿 axis=0：形状变为 (3, 4)

沿 axis=1：形状变为 (2, 4)

沿 axis=2：形状变为 (2, 3)

9. linalg.norm 作用于 3 维以上张量计算的是什么？讲解：它默认计算的是所有元素的平方和的平方根。本质上，它把多维张量“展平”成了一个长长的一维向量，然后计算 $L_2$ 范数。对于矩阵来说，这被称为 Frobenius 范数。

10. 计算大矩阵连乘 $(AB)C$ 和 $A(BC)$ 的内存与速度差异

讲解：矩阵乘法 $M_{m \times n} \times N_{n \times p}$ 的乘法运算量是 $O(mnp)$。结合律决定了结果一致，但运算量天差地别：计算 $(AB)C$：先算 $AB$，运算量 $2^{10} \cdot 2^{16} \cdot 2^5 = 2^{31}$。生成大小为 $2^{10} \times 2^5$ 的中间矩阵（极小）。再算乘 $C$，运算量 $2^{10} \cdot 2^5 \cdot 2^{14} = 2^{29}$。总运算量大约是 $2^{31}$ 级别。计算 $A(BC)$：先算 $BC$，运算量 $2^{16} \cdot 2^5 \cdot 2^{14} = 2^{35}$。生成大小为 $2^{16} \times 2^{14}$ 的巨大中间矩阵。再算乘 $A$，运算量 $2^{10} \cdot 2^{16} \cdot 2^{14} = 2^{40}$。总运算量大约是 $2^{40}$ 级别。结论：$(AB)C$ 的速度要快几百倍，且内存占用极小。这被称为“矩阵链乘法”优化。

11. 计算 $AB$ 与 $AC^\top$ 的速度差异及内存克隆问题

讲解：虽然 $B$ 和 $C^\top$ 形状相同，但在计算机内存中，标准的多维数组是**按行优先（Row-major，C-contiguous）**存储的。计算矩阵乘法时，我们需要取左矩阵的行和右矩阵的列做内积。取 $B$ 的列在内存中是跳跃读取的，缓存命中率低；而 $C^\top$ 的“列”其实就是原始矩阵 $C$ 的“行”，内存中是连续的，读取极快。因此 $AC^\top$ 计算速度通常快于 $AB$。如果不克隆内存直接初始化 $C = B^\top$：此时 $C$ 只是 $B$ 的一个视图（View），改变了步长（Stride）的读取方式，内存并未重新排列。所以计算此时的 $AC^\top$ 就相当于原本的 $AB$，丧失了内存连续性的速度优势。

12. 堆叠三个 $100 \times 200$ 矩阵并还原讲解：如果将 $A, B, C$ 沿着“第三个轴”（即 dim=2）堆叠，张量的形状将变为 (100, 200, 3)。要取出 $B$，只需要对最后一个维度的索引 1（第二个坐标）进行切片。

In [35]:
A, B, C = torch.randn(100, 200), torch.randn(100, 200), torch.randn(100, 200)
# 沿着 dim=2 (第三个轴) 堆叠
X = torch.stack([A, B, C], dim=2)
print(X.shape)  # 输出: torch.Size([100, 200, 3])

# 提取第二个坐标（索引为1）来恢复 B
B_recovered = X[:, :, 1]
print(torch.equal(B, B_recovered))  # 输出: True

torch.Size([100, 200, 3])
True
